#pragma once

enum MBGL_CONSTRAIN_MODE {
  MBGL_CONSTRAIN_MODE_NONE = 0,
  MBGL_CONSTRAIN_MODE_HEIGHT_ONLY = 1,
  MBGL_CONSTRAIN_MODE_WIDTH_AND_HEIGHT = 2,
  MBGL_CONSTRAIN_MODE_SCREEEN = 3,
};

enum MBGL_MAP_MODE {
  MBGL_MAP_MODE_CONTINUOUS = 0,
  MBGL_MAP_MODE_STATIC = 1,
  MBGL_MAP_MODE_TILE = 2,
};

enum MBGL_NORTH_ORIENTATION {
  MBGL_NORTH_ORIENTATION_UPWARDS = 0,
  MBGL_NORTH_ORIENTATION_RIGHTWARDS = 1,
  MBGL_NORTH_ORIENTATION_DOWNWARDS = 2,
  MBGL_NORTH_ORIENTATION_LEFTWARDS = 3,
};

enum MBGL_VIEWPORT_MODE {
  MBGL_VIEWPORT_MODE_DEFAULT = 0,
  MBGL_VIEWPORT_MODE_FLIPPED_Y = 1,
};
